source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!
#xcodeproj 'FreeWeddingApp.xcodeproj'
target 'FreeWeddingApp' do

pod 'Alamofire', '~> 4.4.0'
pod 'HandyJSON', '~> 1.7.1'
pod 'SQLite.swift', '~> 0.11.2'
pod 'Kingfisher', '~> 3.9.1' #swift版本 sdwebimage
pod 'IQKeyboardManagerSwift', '~> 4.0.9'

end
